// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/project_root_version.test.ts.

/** The version of the `@tssuite/project-root` package. */
export const projectRootVersion = '0.0.18';
